# GitHub Action for ApiKey (PHP)
name: Testing PHP
on: [push, pull_request]
jobs:
  ApiKey-ClosedOS:
    name: ApiKey (PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }})
    runs-on: ${{ matrix.operating-system }}
    services:
      redis:
        image: redis
        ports:
          - 6379/tcp
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: false
      matrix:
        operating-system: [
            windows-latest,
            macos-latest,
        ]
        php-versions: [
            '8.0',
            '8.1',
            '8.2',
            '8.3',
            '8.4',
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Docs: https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: pdo_sqlite, redis
          coverage: xdebug

      - name: Test
        run: php --define apc.enable_cli=1 ApiKey.php test

  ApiKey-OpenOS:
    name: ApiKey (PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }})
    runs-on: ${{ matrix.operating-system }}
    services:
      redis:
        image: redis
        ports:
          - 6379/tcp
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: false
      matrix:
        operating-system: [
            ubuntu-latest,
        ]
        php-versions: [
            '8.0',
            '8.1',
            '8.2',
            '8.3',
            '8.4',
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Docs: https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: memcached, redis
          coverage: xdebug

      - name: Setup Memcached
        uses: KeisukeYamashita/memcached-actions@v1

      - name: Test
        run: php --define apc.enable_cli=1 ApiKey.php test